



f=open("rosalind_subs.txt", "r")

s ="CGCGCATCGTCGCATCGCTAGTATAAACCCGTATAGGGTCCCCGCCTCCTCGTTGGCTGCTCAGGGTGGAGCCTAGTCCATTGTATAGCGGTCCAGGCTGCTGCACCGGCGTGACTTCCATGTCACTTGAACGAACCGGGGATTATGCTGTCCCTTATACGTACACTTAGATTCGATTCCTCTTGATAGTGCTCAAAACGGAGCCCGACTGCTAGCAACACTCCCATATGAGAATTGGCTTTGTCCTAAGTTTGCAAGGTTTAGCTAGACCGATATGAAATGGCTATGTGAGGAGACCCAGCGGGAAAACCAGGGGATTAGGAGACGCGCACAATGCAATAACCCTTAACCTCCACAGAAACACTTCCGCTCCCTACCATAAGCCGAACCTCTCTTGGGGCTTAACGGCCGATTCGGGATAATGGCCATTACCCTCTAATCGAAGTGTGCGTATAAAATACATTGCCCACTTAACGACTCGCTCTGTTAGGAGTAAGGTGTGTTCGTAGCATGGGTTGGTCCGGTGTCCTGATGGATTTTCAGGGCTGCAGATGGGTTCCCGGATTGGCATGAGTATCGGTCTGGTGCCTACTCACTCTGCTACTTAACTCACGTAATTTTACAGCTCAATCCAGCGGGTCAAATCTCAGAGGCGTTCATACATGCTATGGGCGACGAGTGTCTAGACGTGTGGCCAACCTAACGTGTCCTTAACGTCTATCGCCGATGTCTTTTGCGTAAATGCCCGGCAGTCTATCAGCTTCAGTTTAAACCTACAAGGAGTTCGATTGGCTTCCCCACGAGGCGGTGCTGGGAAGGGCGCGGATCATCGGACTGGGAGACATAGCGC"
dic={"A":"T", "T":"A", "G":"C", "C":"G"}


for i in range(0,len(s)):
    
    for n in range(4,13):
        rev=[]
        str1=s[i:i+n]
        for m in str1:
            rev.append(dic[m])
        str2="".join(rev)[::-1]
        arr=[]
        if (str1==str2)&((i+n)<=(len(s))):
            arr.append(i+1)
            arr.append(n)
            # print(str1,str2)
            print(*arr)

